development: &default
  adapter: mysql
  host: 127.0.0.1
  encoding: utf8
  pool: 5
  username: root
  database: me_development
  password:

test:
  <<: *default
  username: root
  database: me_test
  password:
